### ISSUE TITLE
No information provided

### ISSUE THREAD

**Issue by sadransh** [gbr1/erwhi-hedgehog-ros#1]
Could you please provide some discription on what does the provided code do?

**Comment by gbr1** [comment]
Hi @sadransh !
Thank you for your interest for my project.
The code provided offer a structure to get the robot working in a complex indoor environment with autonomous navigation.  SLAM methodology is used and RTABmap is the main core.
The robot use UKF to filter visual odometer, wheel odometer and absolute IMU.

**Comment by sadransh** [comment]
yeah! I saw the information on https://gbr1.github.io/erwhi_hedgehog.html 

it's good to add it to the first page of the project. 
have you tried adding t265 as SLAM processor ? Doesn't it make the robot move faster ? and make more accurate mapping?

**Comment by gbr1** [comment]
yes!
There is a branch!
Unfortunately I'm preparing some stuff for Maker Faire Rome (Oct 18-20) and I have not completed the launch file and ukf modifications.
